# Generated by Django 4.2.7 on 2025-12-26 11:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0004_calllog_date_calllog_employee_alter_calllog_status'),
    ]

    operations = [
    ]
