# Generated by Django 4.2.7 on 2025-12-26 11:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0005_auto_20251226_1632'),
    ]

    operations = [
    ]
