# Generated by Django 4.2.7 on 2025-12-29 13:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0011_product_b2b_price_product_b2c_price_and_more'),
    ]

    operations = [
    ]
