# Generated by Django 4.2.7 on 2025-12-30 07:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0013_order_order_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm.order'),
        ),
    ]
