# Generated by Django 4.2.7 on 2025-12-30 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0014_calllog_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='call_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
