# Generated by Django 4.2.7 on 2025-12-31 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0016_customer_created_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='total_order_value',
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Full Paid'), ('Partial', 'Partial'), ('Credit', 'Credit')], default='Paid', max_length=10),
        ),
    ]
