# Generated by Django 4.2.7 on 2026-01-04 14:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0019_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.lead'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='crm.customer'),
        ),
    ]
