# Generated by Django 4.2.7 on 2026-01-04 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0020_calllog_lead_alter_calllog_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='appointment_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
