# Generated by Django 4.2.7 on 2026-01-04 19:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0021_customer_appointment_date_lead_appointment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='assumption2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs_assumption2', to='crm.customerassumption'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='assumption3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs_assumption3', to='crm.customerassumption'),
        ),
    ]
