# Generated by Django 4.2.7 on 2026-01-04 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0022_calllog_assumption2_calllog_assumption3'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerassumption',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
