# Generated by Django 4.2.7 on 2026-01-04 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0024_customerassumption2_customerassumption3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
