# Generated by Django 4.2.7 on 2026-01-05 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0025_customer_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gst_rate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
