# Generated by Django 4.2.7 on 2026-01-06 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0027_gstrate_alter_product_gst_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='appointment_time',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
