# Generated by Django 4.2.7 on 2026-01-09 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0030_customer_area_customer_city_customer_district_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='calllog',
            name='assumption',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='assumption2',
        ),
        migrations.RemoveField(
            model_name='calllog',
            name='assumption3',
        ),
        migrations.AlterField(
            model_name='calllog',
            name='note',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='calllog',
            name='assumption',
            field=models.ManyToManyField(blank=True, to='crm.customerassumption'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='assumption2',
            field=models.ManyToManyField(blank=True, to='crm.customerassumption2'),
        ),
        migrations.AddField(
            model_name='calllog',
            name='assumption3',
            field=models.ManyToManyField(blank=True, to='crm.customerassumption3'),
        ),
    ]
