# Generated by Django 4.2.7 on 2026-01-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0031_remove_calllog_assumption_remove_calllog_assumption2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='contact_type',
            field=models.CharField(choices=[('Customer', 'Customer'), ('Lead', 'Lead')], default='Customer', max_length=20),
        ),
    ]
