# Generated by Django 4.2.7 on 2026-01-12 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0032_customer_contact_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='company_type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
