# Generated by Django 4.2.7 on 2026-01-13 18:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0038_organizationtype_alter_customer_company_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='customer_type',
            field=models.CharField(blank=True, choices=[('Superstockist', 'Superstockist'), ('Wholesaler', 'Wholesaler'), ('End User', 'End User'), ('Consumer', 'Consumer'), ('Distributor', 'Distributor')], max_length=20, null=True),
        ),
    ]
