# Generated by Django 4.2.7 on 2026-01-14 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0040_combinationitem_offer_price_combinationgift'),
    ]

    operations = [
        migrations.AddField(
            model_name='calllog',
            name='saved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('In Progress', 'In Progress'), ('Completed', 'Completed'), ('Follow-up', 'Follow-up')], default='Pending', max_length=50),
        ),
    ]
