# Generated by Django 4.2.7 on 2026-01-15 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0042_user_aadhar_number_user_address_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='cost',
        ),
        migrations.AddField(
            model_name='product',
            name='product_volume',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='product_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
