# Generated by Django 4.2.7 on 2026-01-16 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0043_remove_product_cost_product_product_volume_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
