# Generated by Django 4.2.7 on 2026-01-19 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0046_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='combinationgift',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
    ]
