# Generated by Django 4.2.7 on 2026-02-02 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0047_combinationgift_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hsn',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
