# Generated by Django 4.2.7 on 2026-02-02 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0048_product_hsn'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombination',
            name='combo_weight',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='curriar_dispatch_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='curriar_purchase_point',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
