# Generated by Django 4.2.7 on 2026-02-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0049_productcombination_combo_weight_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
