# Generated by Django 4.2.7 on 2026-03-13 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0051_order_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Full Paid'), ('Partial', 'Partial'), ('Credit', 'Credit'), ('Advance', 'Advance')], default='Paid', max_length=10),
        ),
    ]
