# Generated by Django 4.2.7 on 2026-03-17 17:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0054_order_delivery_area_order_delivery_city_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='applied_combos',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='combo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_items', to='crm.productcombination'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_free',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='is_gift',
            field=models.BooleanField(default=False),
        ),
    ]
