# Generated by Django 5.0.4 on 2026-03-27 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0056_category_parent_product_category1_product_category2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='brand_category',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='brand_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='flavour',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='residual',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
