# Generated by Django 5.0.4 on 2026-03-27 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0057_product_brand_category_product_brand_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='video_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
