# Generated by Django 5.0.4 on 2026-03-30 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0059_product_image1_product_image2_product_image3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='customer',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
