# Generated by Django 5.0.4 on 2026-03-31 12:14

import django.db.models.deletion
from django.db import migrations, models


def convert_brand_data(apps, schema_editor):
    Product = apps.get_model('crm', 'Product')
    Brand = apps.get_model('crm', 'Brand')
    BrandCategory = apps.get_model('crm', 'BrandCategory')
    
    print("\n" + "="*50)
    print("Converting brand data...")
    print("="*50)
    
    # Use raw SQL to get the data since the ORM is confused
    from django.db import connection
    
    # Step 1: Get all brand_name values using raw SQL
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, brand_name FROM crm_product WHERE brand_name IS NOT NULL AND brand_name != ''")
        brand_data = cursor.fetchall()
        print(f"\nFound {len(brand_data)} products with brand_name")
        
        # Create unique brands
        unique_brands = set()
        for _, brand_name in brand_data:
            if brand_name and brand_name.strip():
                unique_brands.add(brand_name.strip())
        
        brand_cache = {}
        for brand_name in unique_brands:
            # Check if brand exists
            cursor.execute("SELECT id FROM brands WHERE name = %s", (brand_name,))
            existing = cursor.fetchone()
            if existing:
                brand_cache[brand_name] = existing[0]
            else:
                # Insert new brand
                cursor.execute(
                    "INSERT INTO brands (name, description, created_at, updated_at) VALUES (%s, %s, GETDATE(), GETDATE())",
                    (brand_name, f'Converted from product brand: {brand_name}')
                )
                cursor.execute("SELECT SCOPE_IDENTITY()")
                brand_id = cursor.fetchone()[0]
                brand_cache[brand_name] = brand_id
                print(f"  Created brand: {brand_name}")
    
    # Step 2: Get all brand_category_old values using raw SQL
    with connection.cursor() as cursor:
        cursor.execute("SELECT id, brand_category_old FROM crm_product WHERE brand_category_old IS NOT NULL AND brand_category_old != ''")
        category_data = cursor.fetchall()
        print(f"\nFound {len(category_data)} products with brand_category")
        
        # Create unique categories
        unique_categories = set()
        for _, category_name in category_data:
            if category_name and category_name.strip():
                unique_categories.add(category_name.strip())
        
        category_cache = {}
        for category_name in unique_categories:
            # Check if category exists
            cursor.execute("SELECT id FROM brand_categories WHERE name = %s", (category_name,))
            existing = cursor.fetchone()
            if existing:
                category_cache[category_name] = existing[0]
            else:
                # Insert new category
                cursor.execute(
                    "INSERT INTO brand_categories (name, description, created_at, updated_at) VALUES (%s, %s, GETDATE(), GETDATE())",
                    (category_name, f'Converted from product category: {category_name}')
                )
                cursor.execute("SELECT SCOPE_IDENTITY()")
                category_id = cursor.fetchone()[0]
                category_cache[category_name] = category_id
                print(f"  Created brand category: {category_name}")
    
    # Step 3: Update products with brand_id
    print("\nUpdating products with brand references...")
    with connection.cursor() as cursor:
        update_count = 0
        for product_id, brand_name in brand_data:
            if brand_name and brand_name.strip() and brand_name.strip() in brand_cache:
                cursor.execute(
                    "UPDATE crm_product SET brand_id = %s WHERE id = %s",
                    (brand_cache[brand_name.strip()], product_id)
                )
                update_count += 1
                if update_count % 100 == 0:
                    print(f"  Updated {update_count} products...")
        print(f"Updated {update_count} products with brand references")
    
    # Step 4: Update products with brand_category_id
    print("\nUpdating products with brand category references...")
    with connection.cursor() as cursor:
        update_count = 0
        for product_id, category_name in category_data:
            if category_name and category_name.strip() and category_name.strip() in category_cache:
                cursor.execute(
                    "UPDATE crm_product SET brand_category_id = %s WHERE id = %s",
                    (category_cache[category_name.strip()], product_id)
                )
                update_count += 1
                if update_count % 100 == 0:
                    print(f"  Updated {update_count} products...")
        print(f"Updated {update_count} products with brand category references")
    
    print("\n" + "="*50)
    print("Data conversion completed!")
    print("="*50 + "\n")


def reverse_conversion(apps, schema_editor):
    # Optional: reverse migration - just skip
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0061_product_category4_alter_product_hsn_and_more'),
    ]

    operations = [
        # Create the new models
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brands',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='BrandCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'brand_categories',
                'ordering': ['name'],
            },
        ),
        
        # Add the brand field as nullable first
        migrations.AddField(
            model_name='product',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm.brand'),
        ),
        
        # Rename the existing brand_category field to preserve data
        migrations.RenameField(
            model_name='product',
            old_name='brand_category',
            new_name='brand_category_old',
        ),
        
        # Add the new brand_category foreign key field
        migrations.AddField(
            model_name='product',
            name='brand_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='crm.brandcategory'),
        ),
        
        # Data migration to convert old data to new foreign keys
        migrations.RunPython(convert_brand_data, reverse_conversion),
        
        # Remove the old brand_name field
        migrations.RemoveField(
            model_name='product',
            name='brand_name',
        ),
        
        # Remove the old brand_category_old field
        migrations.RemoveField(
            model_name='product',
            name='brand_category_old',
        ),
    ]