# Generated by Django 5.0.4 on 2026-04-01 10:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0062_brand_brandcategory_remove_product_brand_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('purchase_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('transport_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('transport_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('labor_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('labor_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('handling_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('handling_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('godown_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('godown_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('delivery_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('delivery_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('packaging_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('packaging_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra1_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('extra1_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('extra2_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('extra2_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('landing_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10)),
                ('landing_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('company_margin_type', models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='percent', max_length=10)),
                ('company_margin_value', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('sale_rate', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('mrp', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True)),
                ('landing_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('calculated_rate', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricings', to='crm.product')),
            ],
            options={
                'unique_together': {('product',)},
            },
        ),
    ]
