# Generated by Django 5.0.4 on 2026-04-02 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0063_productpricing'),
    ]

    operations = [
        migrations.AddField(
            model_name='productpricing',
            name='batch_no',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='productpricing',
            name='mfg_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
