# Generated by Django 5.0.4 on 2026-04-07 13:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0064_productpricing_batch_no_productpricing_mfg_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calllog',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm.customer'),
        ),
        migrations.AlterField(
            model_name='calllog',
            name='lead',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='call_logs', to='crm.lead'),
        ),
    ]
