# Generated by Django 5.0.4 on 2026-04-18 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0065_alter_calllog_customer_alter_calllog_lead'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='contact_person',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
