# Generated by Django 5.0.4 on 2026-04-25 08:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0066_phone_contact_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='OldOrderHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('notes', models.TextField(blank=True, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='old_order_histories', to='crm.customer')),
            ],
            options={
                'verbose_name_plural': 'Old Order Histories',
                'ordering': ['-date'],
            },
        ),
    ]
