# Generated by Django 5.0.4 on 2026-04-27 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0067_oldorderhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='productcombination',
            name='delivery_charge_type',
            field=models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='delivery_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='extra_charge_type',
            field=models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='extra_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='final_combo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='handling_charge_type',
            field=models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='handling_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='manual_combo_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='parking_charge_type',
            field=models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='parking_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='total_charges',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='transportation_charge_type',
            field=models.CharField(choices=[('percent', '%'), ('rupees', '₹')], default='rupees', max_length=10),
        ),
        migrations.AddField(
            model_name='productcombination',
            name='transportation_charge_value',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
