# Generated by Django 5.0.4 on 2026-04-27 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0068_productcombination_delivery_charge_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pointer1',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pointer2',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pointer3',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pointer4',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='pointer5',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
