# Generated by Django 5.0.4 on 2026-04-27 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0069_product_pointer1_product_pointer2_product_pointer3_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='breadth_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Breadth/Width in centimeters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='height_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Height in centimeters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='length_cm',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Length in centimeters', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='packing_weight',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Packing weight in same unit as product_weight', max_digits=10, null=True),
        ),
    ]
