# Generated by Django 5.0.4 on 2026-04-29 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0071_flavour_residual_brandcategory1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='packing_weight_unit',
            field=models.CharField(blank=True, help_text='Unit for packing weight (e.g., kg, g, lb)', max_length=20, null=True),
        ),
    ]
