# Generated by Django 5.0.4 on 2026-04-29 08:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0072_product_packing_weight_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='packing_weight_unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='packing_weight_products', to='crm.unit'),
        ),
    ]
