# Generated by Django 5.0.4 on 2026-04-29 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0073_alter_product_packing_weight_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='unit_type',
            field=models.CharField(choices=[('product', 'Product Unit'), ('packing', 'Packing Unit'), ('both', 'Both')], default='both', max_length=10),
        ),
    ]
