# Generated by Django 5.0.4 on 2026-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0074_unit_unit_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='conversion_to_kg',
            field=models.DecimalField(decimal_places=10, default=1, help_text='Multiply by this to convert to kg', max_digits=20),
        ),
    ]
