# Generated by Django 5.0.4 on 2026-05-24 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0075_unit_conversion_to_kg'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='gstin_no',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
