# Generated by Django 5.0.4 on 2026-07-02 07:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0076_customer_gstin_no'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="Name of the custom role (e.g., 'Data Entry')", max_length=50, unique=True)),
                ('description', models.TextField(blank=True, help_text='Brief description of the role responsibilities', null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(default='Employee', max_length=50),
        ),
        migrations.CreateModel(
            name='RoleFeaturePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(help_text="The key of the feature (e.g., 'create_order')", max_length=50)),
                ('is_enabled', models.BooleanField(default=False, help_text='Whether this feature is enabled for this role')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permissions', to='crm.role')),
            ],
            options={
                'unique_together': {('role', 'feature_key')},
            },
        ),
    ]
