# Generated by Django 5.0.4 on 2026-07-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0077_role_alter_user_role_rolefeaturepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Full Paid'), ('Partial', 'Partial'), ('Credit', 'Credit'), ('Advance', 'Advance'), ('COD', 'COD')], default='Paid', max_length=10),
        ),
    ]
