# Generated by Django 5.0.4 on 2026-07-17 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0079_order_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='mrp',
            field=models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=12, null=True),
        ),
    ]
