# Generated by Django 5.0.4 on 2026-08-20 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crm', '0081_community_language_customer_community_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'ordering': ['id']},
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Full Paid'), ('Partial', 'Partial'), ('Credit', 'Credit'), ('Advance', 'Advance'), ('Advance Payment Received', 'Advance Payment Received'), ('COD', 'COD')], default='Paid', max_length=50),
        ),
    ]
